#!/bin/bash

##variables
  declare -a MYFIELD=(
# TEST
# ANIMATED
"Love, Death & Robots"
"Genndy Tartakovsky’s Primal"
"Farzar"
"The Boys Presents: Diabolical"
"Dallas & Robo"
"Jurassic World Camp Cretaceous"
"Star Trek: Lower Decks"
"Dicktown"
"Archer"
"Triptank"
"Jeff & Some Aliens"
"Bojack Horseman"
"Rick and Morty"
"Solar Opposites"
"Robot Chicken"
"Big Mouth"
"F is for Family"
"Inside Job"
"Mike Tyson Mysteries"
"American Dad"
"Family Guy"
"South Park"
"Futurama"
"The Simpsons"
"Disenchantment"
"Wild Life"
"Q-Force"
"Close Enough"
"Hoops"
"Horsin' Around"
# MARVEL
"WandaVision"
"The Falcon and The Winter Soldier"
"Loki"
"What If...?"
"Hawkeye"
"Moon Knight"
"Ms. Marvel"
"I Am Groot"
"She-Hulk: Attorney at Law"
"Marvel's Spider-Man"
"Marvel's Ant-Man"
"Marvel's Avengers Assemble"
"Marvel's Cloak and Dagger"
"Marvel's Guardians of the Galaxy"
"Marvel's Daredevil"
"Marvel's Luke Cage"
"Marvel's Jessica Jones"
"Marvel's Iron Fist"
"Marvel's The Punisher"
"Marvel's The Defenders"
"Marvel's Runaways"
"The Gifted"
"Legion"
# DC
"Supergirl"
"Krypton"
"Titans"
"Doom Patrol"
"The Flash"
"Peacemaker"
# LIVE ACTION
"Only Murders in the Building"
"Severance"
"Barry"
"The Witcher"
"The Tick"
"Impulse"
"Vinyl"
"Limitless"
"Lost in Space"
"Salvation"
"Foundation"
"Star Trek: Discovery"
"Star Trek: Prodigy"
"Star Trek: Picard"
"Star Trek: Strange New Worlds"
"Stranger Things"
"Westworld"
"Black Mirror"
"Black Monday"
"Mr. Robot"
"Disjointed"
"Silicon Valley"
"The Orville"
"Altered Carbon"
"Future Man"
"Stranger Things"
"What We do in the Shadows"
"Mandalorian"
"Resident Alien"
"The Book of Boba Fett"
"Who Is America"
"Space Force"
"Squid Game"
"Halo"
"The Umbrella Academy"
);
